AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
